config/routes.rb
Rails.application.routes.draw do
  devise_for :sellers
  devise_for :users
  root 'home#index'

end

app/models/seller.rb
class Seller < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
            devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
        end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Welcome to Catchy Craft</h1>
<p>New way to admire Art and Handicraft</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CatchyCraft</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true%>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar">
          <span class="icon-bar">
          <span class="icon-bar">
        </button>
        
        <div class="nav-collapse collapse">
          <%= link_to 'CatchyCraft', root_path, :class => 'brand' %>
        <div class="nav-collapse">
	      <div class="pull-right ">					
  	     <% if user_signed_in? %>
  	       Logged in as <%= current_user.email %> </b>
          <%= link_to "Edit Profile", edit_user_registration_path %>
          <%= link_to 'Log Out', destroy_user_session_path, :method => "delete" %>
         <% else %>
          <%= link_to 'Sell with us' %>
          <%= link_to 'Sign Up', new_user_registration_path %>
    	    <%= link_to 'Sign In', new_user_session_path %>   
         <% end %>
	      </div>
      </div>
	  </div>
	</div>
</div>
</div>
<div class = "container">
	<div class="row">

	<% if flash.notice %>
  		<div class="alert alert-block alert-info">
    	 <button type="button" class="close" data-dismiss="alert">×
    	 <%= flash.notice %>
  		</div>
	<% end %>
	<% if flash.alert %>
  		<div class="alert alert-block alert-error">
    		<button type="button" class="close" data-dismiss="alert">×
    		<%= flash.alert %>
  		</div>
	<% end %>				
	</div>
</div>
<div class="main">
<%= yield %>
</div>

</body>
</html>

app/views/layouts/layout_seller.html.erb
<html>
<head>
  <title>CatchyCraft</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true%>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar">
          <span class="icon-bar">
          <span class="icon-bar">
        </button>
        
        <div class="nav-collapse collapse">
          <%= link_to 'CatchyCraft', root_path, :class => 'brand' %>
        <div class="nav-collapse">
	      <div class="pull-right ">					
  	     <% if user_signed_in? %>
  	       Logged in as <%= current_seller.email %> </b>
          <%= link_to "Edit Profile", edit_seller_registration_path %>
          <%= link_to 'Log Out', destroy_seller_session_path, :method => "delete" %>
         <% else %>
          <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
            <div class="field">
              <%= f.label :email %>
               <%= f.email_field :email, autofocus: true %>
             </div>

          <div class="field">
           <%= f.label :password %>
           <%= f.password_field :password, autocomplete: "off" %>
         </div>

         <% if devise_mapping.rememberable? -%>
          <div class="field">
          <%= f.check_box :remember_me %>
          <%= f.label :remember_me %>
        </div>
       <% end -%>

       <div class="actions">
         <%= f.submit "Log in" %>
      </div>
      <% end %>

    	    </div>
      </div>
	  </div>
	</div>
</div>
</div>
<div class = "container">
	<div class="row">

	<% if flash.notice %>
  		<div class="alert alert-block alert-info">
    	 <button type="button" class="close" data-dismiss="alert">×
    	 <%= flash.notice %>
  		</div>
	<% end %>
	<% if flash.alert %>
  		<div class="alert alert-block alert-error">
    		<button type="button" class="close" data-dismiss="alert">×
    		<%= flash.alert %>
  		</div>
	<% end %>				
	</div>
</div>
<div class="main">
<%= yield %>
</div>

</body>
</html>

app/views/sellers/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>